#  ______                           __  _____ __        __      
# /_  __/___  _____________  ____  / /_/ ___// /_____ _/ /______
#  / / / __ \/ ___/ ___/ _ \/ __ \/ __/\__ \/ __/ __ `/ __/ ___/
# / / / /_/ / /  / /  /  __/ / / / /_ ___/ / /_/ /_/ / /_(__  ) 
#/_/  \____/_/  /_/   \___/_/ /_/\__//____/\__/\__,_/\__/____/  
                                                               
# This is the per-server configuration for TorrentStats: https://github.com/JerichoTorrent/TorrentStats

# The server name is unique; this will be how your split up stats from each server across your network.
# If you want to share statistics, use a remote database (MySQL, MariaDB, etc) for the plugin hook/listener.
server-name: Survival

# Enable plugin hooks. If the plugin is not detected at run-time, it will ignore it. If the plugin fails to
# start, report it on Github.
enabled-hooks:
  mcmmo: true
  evenmorefish: true
  vault: true
  ezchestshop: true
  flightcontrol: true
  thedungeons: true
  betterteams: true
  plotsquared: true
  expbottle: true
  beautyquests: true
  bukkitstats: true # Tracks a select few important stats from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Statistic.html

# Input your MySQL database credentials here. If you're using SQLite, just change the type to sqlite and leave the rest alone.
database:
  type: mysql # or sqlite
  host: localhost
  port: 3306
  name: torrent_stats
  user: root
  password: password

# Your web URL is the base URL for your website.
web-url: "https://torrentsmp.com" # or your dev env URL