name: TorrentStats
main: com.jerichotorrent.torrentstats.TorrentStats
version: ${project.version}
api-version: '1.21'
authors: [JerichoTorrent]
softdepend:
  - Vault
  - mcMMO
  - EvenMoreFish
  - EzChestShop
  - FlightControl
  - TheDungeons
  - BetterTeams
  - PlotSquared
  - ExpBottle
  - BeautyQuests
  - SkyFactionsReborn
  - AdvancedJobs
commands:
  login:
    description: Link your Minecraft account to the website.
    usage: /login
  torrentstats:
    description: TorrentStats debug command
    usage: /torrentstats <debug|reload>
    permission: torrentstats.debug

permissions:
  torrentstats.debug:
    description: Allow use of /torrentstats debug
    default: op
  
  torrentstats.reload:
    description: Reload the TorrentStats config; can only reload server-name and re-parse hooks